### PR TITLE
Use filtered table output to list running Otel containers

### LINKED ISSUE #16: `spin otel cleanup` fails with custom `docker ps` layout
The current implementation of `spin otel cleanup` assumes that the output of `docker ps` contains the name of every container. For users with a custom `docker ps` layout, this could result in no containers being stopped at all.

### PR DESCRIPTION
**Pull request by ThorstenHans**
With this PR, the implementation of `spin otel cleanup` is changed to explicitly set `table` output. By explicitly using the `table` output, the corresponding output will always contain the name of running containers. 

Additionally, a filter condition is added to retrieve only those containers that were spawned by `spin otel setup`.

Fixes #16

### CODE REVIEW

File: cmd/cleanup.go [hunk 1]
```diff
@@ -23,13 +23,10 @@ func getIDs(dockerOutput []byte) []string {
...
 	outputArray := strings.Split(string(dockerOutput), "\n")
 
-	for _, entry := range outputArray {
-		// Each container in the Docker Compose stack will have the name of the directory
-		if strings.Contains(entry, otelConfigDirName) {
-			fields := strings.Fields(entry)
-			if len(fields) > 0 {
-				result = append(result, fields[0])
-			}
+	for _, entry := range outputArray[1:] {
```
Comment (calebschoepp) [inline cmd/cleanup.go:26]: Why from `[1:]` instead of the whole thing now?

**Review by calebschoepp — APPROVED** [review]
Question for understanding but otherwise LGTM

File: cmd/cleanup.go (hunk 1 above)
Comment (ThorstenHans) [reply cmd/cleanup.go:26]: Because line 0 contains the header line

Comment (ThorstenHans) [reply cmd/cleanup.go:26]: And there is no `--no-header` flag we could set

Comment (ThorstenHans) [reply cmd/cleanup.go:26]: sure, thought about that as well

Comment (ThorstenHans) [reply cmd/cleanup.go:28]: Resolved with f359289
